"""Generate one source build identity for both planes before building Main."""

import json
import subprocess
from pathlib import Path

from soma.foundation.strict_json import loads_strict

ROOT = Path(__file__).resolve().parents[1]


def generate(root: Path = ROOT) -> dict:
    def git(*args):
        try:
            return subprocess.check_output(
                ["git", *args], cwd=root, text=True, stderr=subprocess.DEVNULL
            ).strip()
        except (OSError, subprocess.CalledProcessError):
            return None

    repository = git("rev-parse", "--show-toplevel")
    is_checkout = repository is not None and Path(repository).resolve() == root.resolve()
    commit = git("rev-parse", "HEAD") if is_checkout else None
    status = git("status", "--porcelain") if is_checkout else None
    manifest_path = root / "src/core/soma/db/migrations/manifest.json"
    schema_path = root / "src/core/soma/db/schema_manifest.json"
    migration_generation = schema_generation = 0
    if manifest_path.exists() or schema_path.exists():
        manifest = loads_strict(manifest_path.read_text(encoding="utf-8"))
        schema = loads_strict(schema_path.read_text(encoding="utf-8"))
        migration_generation, schema_generation = manifest["generation"], schema["generation"]
        if (
            type(migration_generation) is not int
            or migration_generation < 1
            or type(schema_generation) is not int
            or schema_generation != migration_generation
        ):
            raise ValueError("Contradictory schema/migration build identity")
    value = {
        "application_version": "0.1.0.dev0",
        "runtime_protocol_version": 1,
        "contract_generation": 1,
        "migration_generation": migration_generation,
        "schema_generation": schema_generation,
        "source_commit": commit,
        "dirty": None if status is None else bool(status),
        "build_kind": "source",
    }
    for path, content in {
        root / "src/core/soma/foundation/build/identity.json": json.dumps(value, indent=2) + "\n",
        root
        / "src/main/shared/build/identity.ts": "// Generated by tools/build_identity.py; do not edit.\nexport const buildIdentity = "
        + json.dumps(value, indent=2)
        + " as const;\n",
    }.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    return value


if __name__ == "__main__":
    generate()
